let cities = {
  "Aarhus": "aarhus",
  "Adelaide": "adelaide",
  "Albuquerque": "albuquerque",
  "Almaty": "almaty",
  "Amsterdam": "amsterdam",
  "Anchorage": "anchorage",
  "Andorra": "andorra",
  "Ankara": "ankara",
  "Asheville": "asheville",
  "Asuncion": "asuncion",
  "Athens": "athens",
  "Atlanta": "atlanta",
  "Auckland": "auckland",
  "Austin": "austin",
  "Baku": "baku",
  "Bali": "bali",
  "Bangkok": "bangkok",
  "Barcelona": "barcelona",
  "Beijing": "beijing",
  "Beirut": "beirut",
  "Belfast": "belfast",
  "Belgrade": "belgrade",
  "Belize City": "belize-city",
  "Bengaluru": "bengaluru",
  "Bergen": "bergen",
  "Berlin": "berlin",
  "Bern": "bern",
  "Birmingham": "birmingham",
  "Birmingham, AL": "birmingham-al",
  "Bogota": "bogota",
  "Boise": "boise",
  "Bologna": "bologna",
  "Bordeaux": "bordeaux",
  "Boston": "boston",
  "Boulder": "boulder",
  "Bozeman": "bozeman",
  "Bratislava": "bratislava",
  "Brighton": "brighton",
  "Brisbane": "brisbane",
  "Bristol": "bristol",
  "Brno": "brno",
  "Brussels": "brussels",
  "Bucharest": "bucharest",
  "Budapest": "budapest",
  "Buenos Aires": "buenos-aires",
  "Buffalo": "buffalo",
  "Cairo": "cairo",
  "Calgary": "calgary",
  "Cambridge": "cambridge",
  "Cape Town": "cape-town",
  "Caracas": "caracas",
  "Cardiff": "cardiff",
  "Casablanca": "casablanca",
  "Charleston": "charleston",
  "Charlotte": "charlotte",
  "Chattanooga": "chattanooga",
  "Chennai": "chennai",
  "Chiang Mai": "chiang-mai",
  "Chicago": "chicago",
  "Chisinau": "chisinau",
  "Christchurch": "christchurch",
  "Cincinnati": "cincinnati",
  "Cleveland": "cleveland",
  "Cluj-Napoca": "cluj-napoca",
  "Cologne": "cologne",
  "Colorado Springs": "colorado-springs",
  "Columbus": "columbus",
  "Copenhagen": "copenhagen",
  "Cork": "cork",
  "Curitiba": "curitiba",
  "Dallas": "dallas",
  "Dar es Salaam": "dar-es-salaam",
  "Delhi": "delhi",
  "Denver": "denver",
  "Des Moines": "des-moines",
  "Detroit": "detroit",
  "Doha": "doha",
  "Dresden": "dresden",
  "Dubai": "dubai",
  "Dublin": "dublin",
  "Dusseldorf": "dusseldorf",
  "Edinburgh": "edinburgh",
  "Edmonton": "edmonton",
  "Eindhoven": "eindhoven",
  "Eugene": "eugene",
  "Florence": "florence",
  "Florianopolis": "florianopolis",
  "Fort Collins": "fort-collins",
  "Frankfurt": "frankfurt",
  "Fukuoka": "fukuoka",
  "Galway": "gaillimh",
  "Gdansk": "gdansk",
  "Geneva": "geneva",
  "Gibraltar": "gibraltar",
  "Glasgow": "glasgow",
  "Gothenburg": "gothenburg",
  "Grenoble": "grenoble",
  "Guadalajara": "guadalajara",
  "Guatemala City": "guatemala-city",
  "Halifax": "halifax",
  "Hamburg": "hamburg",
  "Hannover": "hannover",
  "Havana": "havana",
  "Helsinki": "helsinki",
  "Ho Chi Minh City": "ho-chi-minh-city",
  "Hong Kong": "hong-kong",
  "Honolulu": "honolulu",
  "Houston": "houston",
  "Hyderabad": "hyderabad",
  "Indianapolis": "indianapolis",
  "Innsbruck": "innsbruck",
  "Istanbul": "istanbul",
  "Jacksonville": "jacksonville",
  "Jakarta": "jakarta",
  "Johannesburg": "johannesburg",
  "Kansas City": "kansas-city",
  "Karlsruhe": "karlsruhe",
  "Kathmandu": "kathmandu",
  "Kiev": "kiev",
  "Kingston": "kingston",
  "Knoxville": "knoxville",
  "Krakow": "krakow",
  "Kuala Lumpur": "kuala-lumpur",
  "Kyoto": "kyoto",
  "Lagos": "lagos",
  "La Paz": "la-paz",
  "Las Palmas de Gran Canaria": "las-palmas-de-gran-canaria",
  "Las Vegas": "las-vegas",
  "Lausanne": "lausanne",
  "Leeds": "leeds",
  "Leipzig": "leipzig",
  "Lille": "lille",
  "Lima": "lima",
  "Lisbon": "lisbon",
  "Liverpool": "liverpool",
  "Ljubljana": "ljubljana",
  "London": "london",
  "Los Angeles": "los-angeles",
  "Louisville": "louisville",
  "Luxembourg": "luxembourg",
  "Lviv": "lviv",
  "Lyon": "lyon",
  "Madison": "madison",
  "Madrid": "madrid",
  "Malaga": "malaga",
  "Malmo": "malmo",
  "Managua": "managua",
  "Manchester": "manchester",
  "Manila": "manila",
  "Marseille": "marseille",
  "Medellin": "medellin",
  "Melbourne": "melbourne",
  "Memphis": "memphis",
  "Mexico City": "mexico-city",
  "Miami": "miami",
  "Milan": "milan",
  "Milwaukee": "milwaukee",
  "Minneapolis-Saint Paul": "minneapolis-saint-paul",
  "Minsk": "minsk",
  "Montevideo": "montevideo",
  "Montreal": "montreal",
  "Moscow": "moscow",
  "Mumbai": "mumbai",
  "Munich": "munich",
  "Nairobi": "nairobi",
  "Nantes": "nantes",
  "Naples": "naples",
  "Nashville": "nashville",
  "New Orleans": "new-orleans",
  "New York": "new-york",
  "Nice": "nice",
  "Nicosia": "nicosia",
  "Oklahoma City": "oklahoma-city",
  "Omaha": "omaha",
  "Orlando": "orlando",
  "Osaka": "osaka",
  "Oslo": "oslo",
  "Ottawa": "ottawa",
  "Oulu": "oulu",
  "Oxford": "oxford",
  "Palo Alto": "palo-alto",
  "Panama": "panama",
  "Paris": "paris",
  "Perth": "perth",
  "Philadelphia": "philadelphia",
  "Phnom Penh": "phnom-penh",
  "Phoenix": "phoenix",
  "Phuket": "phuket",
  "Pittsburgh": "pittsburgh",
  "Portland, ME": "portland-me",
  "Portland, OR": "portland-or",
  "Porto": "porto",
  "Porto Alegre": "porto-alegre",
  "Prague": "prague",
  "Providence": "providence",
  "Quebec": "quebec",
  "Quito": "quito",
  "Raleigh": "raleigh",
  "Reykjavik": "reykjavik",
  "Richmond": "richmond",
  "Riga": "riga",
  "Rio De Janeiro": "rio-de-janeiro",
  "Riyadh": "riyadh",
  "Rochester": "rochester",
  "Rome": "rome",
  "Rotterdam": "rotterdam",
  "Saint Petersburg": "saint-petersburg",
  "Salt Lake City": "salt-lake-city",
  "San Antonio": "san-antonio",
  "San Diego": "san-diego",
  "San Francisco Bay Area": "san-francisco-bay-area",
  "San Jose": "san-jose",
  "San Juan": "san-juan",
  "San Luis Obispo": "san-luis-obispo",
  "San Salvador": "san-salvador",
  "Santiago": "santiago",
  "Santo Domingo": "santo-domingo",
  "Sao Paulo": "sao-paulo",
  "Sarajevo": "sarajevo",
  "Saskatoon": "saskatoon",
  "Seattle": "seattle",
  "Seoul": "seoul",
  "Seville": "seville",
  "Shanghai": "shanghai",
  "Singapore": "singapore",
  "Skopje": "skopje",
  "Sofia": "sofia",
  "St. Louis": "st-louis",
  "Stockholm": "stockholm",
  "Stuttgart": "stuttgart",
  "Sydney": "sydney",
  "Taipei": "taipei",
  "Tallinn": "tallinn",
  "Tampa Bay Area": "tampa-bay-area",
  "Tampere": "tampere",
  "Tartu": "tartu",
  "Tashkent": "tashkent",
  "Tbilisi": "tbilisi",
  "Tehran": "tehran",
  "Tel Aviv": "tel-aviv",
  "The Hague": "the-hague",
  "Thessaloniki": "thessaloniki",
  "Tokyo": "tokyo",
  "Toronto": "toronto",
  "Toulouse": "toulouse",
  "Tunis": "tunis",
  "Turin": "turin",
  "Turku": "turku",
  "Uppsala": "uppsala",
  "Utrecht": "utrecht",
  "Valencia": "valencia",
  "Valletta": "valletta",
  "Vancouver": "vancouver",
  "Victoria": "victoria",
  "Vienna": "vienna",
  "Vilnius": "vilnius",
  "Warsaw": "warsaw",
  "Washington, D.C.": "washington-dc",
  "Wellington": "wellington",
  "Winnipeg": "winnipeg",
  "Wroclaw": "wroclaw",
  "Yerevan": "yerevan",
  "Zagreb": "zagreb",
  "Zurich": "zurich"
}

/*{
  "Aarhus": "Aarhus",
  "Adelaide": "Adelaide",
  "Albuquerque": "Albuquerque",
  "Almaty": "Almaty",
  "Amsterdam": "Amsterdam",
  "Anchorage": "Anchorage",
  "Andorra": "Andorra",
  "Ankara": "Ankara",
  "Asheville": "Asheville",
  "Asuncion": "Asuncion",
  "Athens": "Athens",
  "Atlanta": "Atlanta",
  "Auckland": "Auckland",
  "Austin": "Austin",
  "Baku": "Baku",
  "Bali": "Bali",
  "Bangkok": "Bangkok",
  "Barcelona": "Barcelona",
  "Beijing": "Beijing",
  "Beirut": "Beirut",
  "Belfast": "Belfast",
  "Belgrade": "Belgrade",
  "Belize City": "Belize City",
  "Bengaluru": "Bengaluru",
  "Bergen": "Bergen",
  "Berlin": "Berlin",
  "Bern": "Bern",
  "Birmingham": "Birmingham",
  "Birmingham, AL": "Birmingham, AL",
  "Bogota": "Bogota",
  "Boise": "Boise",
  "Bologna": "Bologna",
  "Bordeaux": "Bordeaux",
  "Boston": "Boston",
  "Boulder": "Boulder",
  "Bozeman": "Bozeman",
  "Bratislava": "Bratislava",
  "Brighton": "Brighton",
  "Brisbane": "Brisbane",
  "Bristol": "Bristol",
  "Brno": "Brno",
  "Brussels": "Brussels",
  "Bucharest": "Bucharest",
  "Budapest": "Budapest",
  "Buenos Aires": "Buenos Aires",
  "Buffalo": "Buffalo",
  "Cairo": "Cairo",
  "Calgary": "Calgary",
  "Cambridge": "Cambridge",
  "Cape Town": "Cape Town",
  "Caracas": "Caracas",
  "Cardiff": "Cardiff",
  "Casablanca": "Casablanca",
  "Charleston": "Charleston",
  "Charlotte": "Charlotte",
  "Chattanooga": "Chattanooga",
  "Chennai": "Chennai",
  "Chiang Mai": "Chiang Mai",
  "Chicago": "Chicago",
  "Chisinau": "Chisinau",
  "Christchurch": "Christchurch",
  "Cincinnati": "Cincinnati",
  "Cleveland": "Cleveland",
  "Cluj-Napoca": "Cluj-Napoca",
  "Cologne": "Cologne",
  "Colorado Springs": "Colorado Springs",
  "Columbus": "Columbus",
  "Copenhagen": "Copenhagen",
  "Cork": "Cork",
  "Curitiba": "Curitiba",
  "Dallas": "Dallas",
  "Dar es Salaam": "Dar es Salaam",
  "Delhi": "Delhi",
  "Denver": "Denver",
  "Des Moines": "Des Moines",
  "Detroit": "Detroit",
  "Doha": "Doha",
  "Dresden": "Dresden",
  "Dubai": "Dubai",
  "Dublin": "Dublin",
  "Dusseldorf": "Dusseldorf",
  "Edinburgh": "Edinburgh",
  "Edmonton": "Edmonton",
  "Eindhoven": "Eindhoven",
  "Eugene": "Eugene",
  "Florence": "Florence",
  "Florianopolis": "Florianopolis",
  "Fort Collins": "Fort Collins",
  "Frankfurt": "Frankfurt",
  "Fukuoka": "Fukuoka",
  "Galway": "Galway",
  "Gdansk": "Gdansk",
  "Geneva": "Geneva",
  "Gibraltar": "Gibraltar",
  "Glasgow": "Glasgow",
  "Gothenburg": "Gothenburg",
  "Grenoble": "Grenoble",
  "Guadalajara": "Guadalajara",
  "Guatemala City": "Guatemala City",
  "Halifax": "Halifax",
  "Hamburg": "Hamburg",
  "Hannover": "Hannover",
  "Havana": "Havana",
  "Helsinki": "Helsinki",
  "Ho Chi Minh City": "Ho Chi Minh City",
  "Hong Kong": "Hong Kong",
  "Honolulu": "Honolulu",
  "Houston": "Houston",
  "Hyderabad": "Hyderabad",
  "Indianapolis": "Indianapolis",
  "Innsbruck": "Innsbruck",
  "Istanbul": "Istanbul",
  "Jacksonville": "Jacksonville",
  "Jakarta": "Jakarta",
  "Johannesburg": "Johannesburg",
  "Kansas City": "Kansas City",
  "Karlsruhe": "Karlsruhe",
  "Kathmandu": "Kathmandu",
  "Kiev": "Kiev",
  "Kingston": "Kingston",
  "Knoxville": "Knoxville",
  "Krakow": "Krakow",
  "Kuala Lumpur": "Kuala Lumpur",
  "Kyoto": "Kyoto",
  "Lagos": "Lagos",
  "La Paz": "La Paz",
  "Las Palmas de Gran Canaria": "Las Palmas de Gran Canaria",
  "Las Vegas": "Las Vegas",
  "Lausanne": "Lausanne",
  "Leeds": "Leeds",
  "Leipzig": "Leipzig",
  "Lille": "Lille",
  "Lima": "Lima",
  "Lisbon": "Lisbon",
  "Liverpool": "Liverpool",
  "Ljubljana": "Ljubljana",
  "London": "London",
  "Los Angeles": "Los Angeles",
  "Louisville": "Louisville",
  "Luxembourg": "Luxembourg",
  "Lviv": "Lviv",
  "Lyon": "Lyon",
  "Madison": "Madison",
  "Madrid": "Madrid",
  "Malaga": "Malaga",
  "Malmo": "Malmo",
  "Managua": "Managua",
  "Manchester": "Manchester",
  "Manila": "Manila",
  "Marseille": "Marseille",
  "Medellin": "Medellin",
  "Melbourne": "Melbourne",
  "Memphis": "Memphis",
  "Mexico City": "Mexico City",
  "Miami": "Miami",
  "Milan": "Milan",
  "Milwaukee": "Milwaukee",
  "Minneapolis-Saint Paul": "Minneapolis-Saint Paul",
  "Minsk": "Minsk",
  "Montevideo": "Montevideo",
  "Montreal": "Montreal",
  "Moscow": "Moscow",
  "Mumbai": "Mumbai",
  "Munich": "Munich",
  "Nairobi": "Nairobi",
  "Nantes": "Nantes",
  "Naples": "Naples",
  "Nashville": "Nashville",
  "New Orleans": "New Orleans",
  "New York": "New York",
  "Nice": "Nice",
  "Nicosia": "Nicosia",
  "Oklahoma City": "Oklahoma City",
  "Omaha": "Omaha",
  "Orlando": "Orlando",
  "Osaka": "Osaka",
  "Oslo": "Oslo",
  "Ottawa": "Ottawa",
  "Oulu": "Oulu",
  "Oxford": "Oxford",
  "Palo Alto": "Palo Alto",
  "Panama": "Panama",
  "Paris": "Paris",
  "Perth": "Perth",
  "Philadelphia": "Philadelphia",
  "Phnom Penh": "Phnom Penh",
  "Phoenix": "Phoenix",
  "Phuket": "Phuket",
  "Pittsburgh": "Pittsburgh",
  "Portland, ME": "Portland, ME",
  "Portland, OR": "Portland, OR",
  "Porto": "Porto",
  "Porto Alegre": "Porto Alegre",
  "Prague": "Prague",
  "Providence": "Providence",
  "Quebec": "Quebec",
  "Quito": "Quito",
  "Raleigh": "Raleigh",
  "Reykjavik": "Reykjavik",
  "Richmond": "Richmond",
  "Riga": "Riga",
  "Rio De Janeiro": "Rio De Janeiro",
  "Riyadh": "Riyadh",
  "Rochester": "Rochester",
  "Rome": "Rome",
  "Rotterdam": "Rotterdam",
  "Saint Petersburg": "Saint Petersburg",
  "Salt Lake City": "Salt Lake City",
  "San Antonio": "San Antonio",
  "San Diego": "San Diego",
  "San Francisco Bay Area": "San Francisco Bay Area",
  "San Jose": "San Jose",
  "San Juan": "San Juan",
  "San Luis Obispo": "San Luis Obispo",
  "San Salvador": "San Salvador",
  "Santiago": "Santiago",
  "Santo Domingo": "Santo Domingo",
  "Sao Paulo": "Sao Paulo",
  "Sarajevo": "Sarajevo",
  "Saskatoon": "Saskatoon",
  "Seattle": "Seattle",
  "Seoul": "Seoul",
  "Seville": "Seville",
  "Shanghai": "Shanghai",
  "Singapore": "Singapore",
  "Skopje": "Skopje",
  "Sofia": "Sofia",
  "St. Louis": "St. Louis",
  "Stockholm": "Stockholm",
  "Stuttgart": "Stuttgart",
  "Sydney": "Sydney",
  "Taipei": "Taipei",
  "Tallinn": "Tallinn",
  "Tampa Bay Area": "Tampa Bay Area",
  "Tampere": "Tampere",
  "Tartu": "Tartu",
  "Tashkent": "Tashkent",
  "Tbilisi": "Tbilisi",
  "Tehran": "Tehran",
  "Tel Aviv": "Tel Aviv",
  "The Hague": "The Hague",
  "Thessaloniki": "Thessaloniki",
  "Tokyo": "Tokyo",
  "Toronto": "Toronto",
  "Toulouse": "Toulouse",
  "Tunis": "Tunis",
  "Turin": "Turin",
  "Turku": "Turku",
  "Uppsala": "Uppsala",
  "Utrecht": "Utrecht",
  "Valencia": "Valencia",
  "Valletta": "Valletta",
  "Vancouver": "Vancouver",
  "Victoria": "Victoria",
  "Vienna": "Vienna",
  "Vilnius": "Vilnius",
  "Warsaw": "Warsaw",
  "Washington, D.C.": "Washington, D.C.",
  "Wellington": "Wellington",
  "Winnipeg": "Winnipeg",
  "Wroclaw": "Wroclaw",
  "Yerevan": "Yerevan",
  "Zagreb": "Zagreb",
  "Zurich": "Zurich",
}*/
